application/RFGram/application/routes/views.py
from flask import Blueprint, render_template, redirect, url_for, flash, request, jsonify
from flask_login import login_user, current_user, logout_user, login_required
from application.routes.imports import *

views = Blueprint('views', __name__)


@views.route("/", methods=['GET', 'POST'])
def home():
    if request.method == 'GET':
        if not current_user.is_authenticated:
            return redirect(url_for('views.register'))
        return render_template("home.html", title="RFGram", get_file_url=get_file_url)

    if request.method == 'POST':
        start = int(request.form.get('start') or 1)
        posts = current_user.get_followed_posts().paginate(page=start, per_page=2, count=False).items

        result = []
        for post in posts:

            comments = []
            for comment in post.get_comments(limit=2):
                comments.append(
                    {
                        'cid': comment.cid,
                        'content': comment.content,
                        'post_id': comment.post_id,
                        'author':
                            {
                                'uid': comment.author.uid,
                                'username': comment.author.username,
                                'image_file': get_file_url('profile_pics/' + comment.author.image_file),
                                'user_url': url_for('views.get_user', username=comment.author.username)
                            }
                    }
                )

            result.append(
                {
                    'pid': post.pid,
                    'content': post.content,
                    'media': get_file_url('media/' + post.media),
                    'date_posted': post.date_posted,
                    'post_url': url_for('views.get_post', post_id=post.pid),
                    'liked': post.user_liked(current_user),
                    'like_count': post.get_likes_count(),
                    'timeago': post.get_timeago(),
                    'author':
                        {
                            'uid': post.author.uid,
                            'username': post.author.username,
                            'image_file': get_file_url('profile_pics/' + post.author.image_file),
                            'user_url': url_for('views.get_user', username=post.author.username)
                        },
                    'comment_count': post.comments_count(),
                    'comments': comments
                }
            )
        status = True
        return jsonify(result=result, success=status)


@views.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('views.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash("Account registerd sucessfully. You can now login", 'success')
        return redirect(url_for('views.login'))
    return render_template("register.html", title="Register", form=form, get_file_url=get_file_url)


@views.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('views.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and user.password == form.password.data:
            login_user(user, remember=form.remember.data)
            flash("You have been logged in successfully", 'success')

            next_page = request.args.get('next')

            return redirect(next_page or url_for('views.home'))
        else:
            flash("Username or Password is incorrect", 'danger')
            return redirect(url_for('views.login'))
    return render_template("login.html", title="Login", form=form)


@views.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('views.register'))


@views.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        media = save_media(form.media.data)
        post = Post(content=form.content.data, media=media, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash("Posted successfully", 'success')
        return redirect(url_for('views.home'))
    return render_template("new_post.html", title="RFGram", form=form, get_file_url=get_file_url)


@views.route("/user/<string:username>")
def get_user(username):
    user = User.query.filter_by(username=username).first_or_404()
    posts = user.posts
    posts.reverse()
    return render_template("user.html", title=user.username, posts=posts, user=user, get_file_url=get_file_url)


@views.route("/post/id/<int:post_id>")
def get_post(post_id):
    post = Post.query.get_or_404(int(post_id))

    return render_template("post.html", title="RFGram", post=post, get_file_url=get_file_url)


@views.route("/post/<int:post_id>/delete")
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)

    if post.author == current_user:
        db.session.query(Comment).filter(Comment.post_id == post.pid).delete()
        db.session.query(Notif).filter(Notif.post_id == post.pid).delete()
        delete_file(post.media)
        db.session.delete(post)
        db.session.commit()
        flash("Post deleted", 'success')
        return redirect(url_for('views.home'))
    else:
        flash("You don't have delete priviledge for that post!", 'danger')
        return redirect(url_for('views.home'))


@views.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = AccountUpdateForm()

    if form.validate_on_submit():
        current_user.image_file = save_picture(form.picture.data, 'pfp')
        current_user.username = form.username.data
        db.session.commit()
        flash("Account updated", 'success')
        return redirect(url_for('views.account'))

    if request.method == 'GET':
        form.username.data = current_user.username

    return render_template("account.html", title='Account',
                           form=form, image_url=current_user.image_file, get_file_url=get_file_url)


@views.route("/follow", methods=['GET', 'POST'])
@login_required
def follow_user():
    if request.method == 'GET':
        username = request.args.get('username')
    else:
        username = request.form['username']
    print(username)
    user = User.query.filter_by(username=username).first()
    current_user.follow(user)
    db.session.commit()

    return jsonify(result=username + " followed")


@views.route("/unfollow", methods=['POST'])
@login_required
def unfollow_user():
    username = request.form['username']
    user = User.query.filter_by(username=username).first()
    current_user.unfollow(user)
    db.session.commit()
    print(username)

    return jsonify(result=username + " unfollowed")


@views.route("/post/<int:post_id>/like", methods=['GET', 'POST'])
@login_required
def post_likes(post_id):
    post = Post.query.get(int(post_id))
    r = post.like_post(current_user)

    if post.author != current_user:
        if r == "like":
            n = Notif.add_notif(current_user, post, 'liked')
            db.session.add(n)

    db.session.commit()
    return jsonify(result=post.get_likes_count())


@views.route("/comment/<int:post_id>", methods=['POST'])
@login_required
def make_comment(post_id):
    content = request.form['msg']
    post = Post.query.get(int(post_id))
    if post:
        c = Comment(content=content, author=current_user, post_id=post_id)
        db.session.add(c)

        if post.author != current_user:
            n = Notif.add_notif(current_user, post, 'commented on')
            db.session.add(n)

        db.session.commit()

        return jsonify(username=current_user.username,
                       user_url=url_for('views.get_user', username=current_user.username),
                       content=content, cid=c.cid, date_posted=c.date_posted.strftime('%d-%m-%Y'))


@views.route("/comment/<int:com_id>/delete")
@login_required
def delete_comment(com_id):
    com = Comment.query.get_or_404(com_id)
    if com.author == current_user:
        db.session.delete(com)
        db.session.commit()

    return jsonify(result='')


@views.route("/explore", methods=['GET', 'POST'])
def explore():
    if request.method == 'GET':
        if not current_user.is_authenticated:
            return redirect(url_for('views.register'))
        return render_template("explore.html", title="Explore", get_file_url=get_file_url)

    if request.method == 'POST':
        start = int(request.form.get('start') or 1)
        posts = Post.query.paginate(page=start, per_page=3, count=False).items

        result = []
        for post in posts:
            result.append(
                {
                    'media': get_file_url('media/mid' + post.media),
                    'post_url': url_for('views.get_post', post_id=post.pid),
                }
            )
        status = True
        return jsonify(result=result, success=status)

application/RFGram/application/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset>
                <legend>Update Account Info</legend>
                <div class="float-left col-md-1">
                    <img  class="rounded" src="{{ get_file_url('profile_pics/' + current_user.image_file) }}">
                </div>
                <div class="float-right">
                    <div class="form-group" >
                        {{ form.username.label() }}
                        {{ form.username(class="form-control", placeholder="Username") }}
                        <div>
                            {% if form.username.errors %}
                                {% for error in form.username.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group">
                        {{ form.picture.label() }}
                        {{ form.picture(class="form-control-file") }}
                        <div>
                            {% if form.picture.errors %}
                                {% for error in form.picture.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                    <div>
                        {{ form.submit(class="btn btn-primary") }}
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
{% endblock %}

application/RFGram/application/templates/explore.html
{% extends "layout.html" %}
{% block otherstuff %}
<script>
        let page_count = 1;
        let end_reached = false;
    
        document.addEventListener('DOMContentLoaded', () => {
            load_posts(page_count++);

            window.onscroll = () => {
                if(window.innerHeight + window.scrollY >= document.body.offsetHeight && end_reached == false) {
                    load_posts(page_count++);
                }
            }; 
        });


        function load_posts(start) {
            const req = new XMLHttpRequest();
            req.open('POST', $SCRIPT_ROOT + '/explore')

            req.onload = () => {
                const data = JSON.parse(req.responseText);
                
                if (data.success) {
                    if(data.result.length === 0) {
                        end_reached = true;
                        return false;
                    }
                    data.result.forEach(post => {
                        const content = explore_template(post);
                        $('#posts').append(content);
                    });

                }
                else
                    alert("Something went wrong", data.result);
            };

            const param = new FormData();
            param.append('start', start);

            req.send(param);
        };
    
    </script>



<div class="col-10">
    <h4 class="text-muted">Explore</h4>
    <hr>
    
    <div class="row row-cols-3 mb-4" id="posts">
    </div>
</div>

{% endblock otherstuff %}

application/RFGram/application/templates/home.html
{% extends "layout.html" %}
{% block content %}
    <style>
        .special {
            margin-right: 25%;
        }
    </style>
    <script>
        let page_count = 1;
        let end_reached = false;
    
        document.addEventListener('DOMContentLoaded', () => {
            load_posts(page_count++);

            window.onscroll = () => {
                if(window.innerHeight + window.scrollY >= document.body.offsetHeight && end_reached == false) {
                    load_posts(page_count++);
                }
            }; 
        });


        function load_posts(start) {
            const req = new XMLHttpRequest();
            req.open('POST', $SCRIPT_ROOT + '/')

            req.onload = () => {
                const data = JSON.parse(req.responseText);
                
                if (data.success) {
                    if(data.result.length === 0) {
                        end_reached = true;
                        return false;
                    }
                    data.result.forEach(post => {
                        const content = template(post);
                        $('.special').append(content);
                        document.querySelector(`#sh-${post.pid}`).onclick = link_share;
                        document.querySelector(`#l-${post.pid}`).onclick = like_post;
                        document.querySelector(`#c-${post.pid}`).onclick = comment_handler;
                        document.querySelector(`#c-${post.pid}`).disabled = true;
                        document.querySelector(`#comment-on-${post.pid}`).onkeyup = enable_disable_button;
                    });

                }
                else
                    alert("Something went wrong", data.result);
            };

            const param = new FormData();
            param.append('start', start);

            req.send(param);
        };
    
    </script>

{% endblock content %}
{% block sidebar %}
<div class="col-md-3 sidebar" style="position: fixed; float: right; right: 11%;">
    <div class="content-section">
    <h4 class="pb-2">
        <img  class="side-account-img rounded-circle" src="{{get_file_url('profile_pics/' + current_user.image_file)}}">
        <a class = "text-dark" href="{{ url_for('views.get_user', username=current_user.username) }}">{{ current_user.username }}</a>
    </h4>
    <small class='text-muted text-uppercase'>Suggestions for you to follow</small>
    <ul class="list-group suggs">
        {% for user in current_user.get_user_suggestion() %}
            <li class="list-group-item list-group-item">
                <img  class="account-img rounded-circle" src="{{get_file_url('profile_pics/' + user.image_file) }}">
                <a id="flw-{{user.uid}}" class="text-dark user-link" href="{{ url_for('views.get_user', username=user.username) }}">
                    {{ user.username }}
                </a>
                {% if current_user.is_following(user) %}
                    <a href="" class="mt-1 float-right flw-sug text-secondary" id="s-{{user.uid}}">Following</a>
                {% elif user != current_user %}
                    <a href="" class="mt-1 float-right flw-sug text-primary" id="s-{{user.uid}}">Follow</a>
                {% endif %}
                
            </li>
        {% else %}
            <small class="text-muted">You've followed everyone! Enjoy asshole.</small>
        {% endfor %}
    </ul>
    </div>
</div>
{% endblock sidebar %} 

application/RFGram/application/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    <script type=text/javascript src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    
    <script src="https://kit.fontawesome.com/6cd5fe2e76.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>


    <script type=text/javascript>
      $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
    </script>
 
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>RFGram</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-light border-bottom fixed-top">
          <div class="container">
            <a class="navbar-brand mr-4" href="/">RFGram</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
              </div>
              <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                  <a class="nav-item nav-link nav-icons" title="Home" href="{{ url_for('views.home') }}">
                    <i class="fa fa-home" aria-hidden="true"></i>
                  </a>
                  <a class="nav-item nav-link nav-icons" title="Explore" href="{{ url_for('views.explore') }}">
                    <i class="fa fa-compass" aria-hidden="true"></i>
                  </a>
                  <a class="nav-item nav-link nav-icons" title="New Post" href="{{ url_for('views.new_post') }}">
                    <i class="far fa-edit"></i>
                  </a>
                  <a class="nav-item nav-link nav-icons" title="Account" href="{{ url_for('views.account') }}">
                    <i class="far fa-user-circle"></i>
                  </a>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle nav-icons" href="#"  title="Notifications" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      {% if current_user.new_notif() %}<span class="text-danger">* </span>{% endif %}
                      <i class="fa fa-bell-o"></i>
                    </a>
                    <div class="dropdown-menu notif" aria-labelledby="navbarDropdown">
                      {% if current_user.new_notif() %}
                        {% for notif in current_user.get_notifs() %}
                          <a class="dropdown-item bg-light" href="{{url_for('get_post', post_id=notif.post_id)}}">
                            <img  class="account-img rounded" src="{{ url_for('static', filename='media/thumb' + notif.post.media) }}">

                            <small><span class="font-weight-bold">{{ notif.author }}</span> {{ notif.msg }} your post.</small>
                          </a>
                        {% endfor %}
                      {% endif %}
                      {% for notif in current_user.get_old_notifs() %}
                        <a class="dropdown-item" href="{{ url_for('views.get_post', post_id=notif.post_id) }}">
                          <img  class="account-img rounded" src="{{ get_file_url('media/thumb' + notif.post.media) }}">

                          <small><span class="font-weight-bold">{{ notif.author }}</span> {{ notif.msg }} your post.</small>
                        </a>
                      {% else %} 
                      <small class="text-muted" style="margin-left:7px;">No new notifications</small>
                      {% endfor %}
                    </div>
                  </li>
                  <a class="nav-item nav-link nav-icons" title="Logout" href="{{ url_for('views.logout') }}">
                    <i class="fa fa-sign-out"></i>
                  </a>
                {% else %}
                  <a class="nav-item nav-link" href="{{ url_for('views.login') }}">Login</a>
                  <a class="nav-item nav-link" href="{{ url_for('views.register') }}">Register</a>
                {% endif %}
              </div>
            </div>
          </div>
        </nav>
    </header>
    <main role="main" class="container">
        <div class="row justify-content-md-center main-content">
          {% block otherstuff %} {% endblock otherstuff %}
            <div class="col-md-7 special">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                                {{ message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endfor %}
                    {% endif%}
                {% endwith %}
                {% block content %} {% endblock content %}
              </div>
              {% block sidebar %} {% endblock sidebar %}
          </div>
    </main>
</body>

<script src="{{ url_for('static', filename='main.js') }}"></script>
</html>

application/RFGram/application/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="login-form">
        <div class="card" style="width:17rem;">
            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <div class="card-header">
                    <h5 class="card-titile text-center">Sign In</h5>
                </div>
                <fieldset class="card-body">
                    <div class="form-group">
                        {{ form.username(class="form-control rounded-0", placeholder="Username") }}
                        {% if form.username.errors %}
                            <small id="emailHelp" class="form-text text-muted">
                                {% for error in form.username.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </small>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.password(class="form-control rounded-0", placeholder="Password") }}
                        {% if form.password.errors %}
                            <small id="emailHelp" class="form-text text-muted">
                                {% for error in form.password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </small>
                        {% endif %}
                    </div>
                    <div class="form-group form-check">
                        {{ form.remember(class="form-check-input") }} {{ form.remember.label(class="form-check-label mt-1") }}
                    </div>

                <ul class="list-group list-group-flush">

                    {{ form.submit(class="btn btn-primary") }}
                    <li class="list-group-item text-center ">
                        <small>Don't have an account? <a href="{{ url_for('views.register') }}">Register</a></small>
                    </li>
                </ul>
                </fieldset>
            </form>
        </div>
    </div>
{% endblock content %}

application/RFGram/application/templates/new_post.html
{% extends "layout.html" %}
{% block content %}
<form method="POST" action="" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <div class="card">
        <div class="card-body">
            <div class="input-group px-2 py-2 bg-light border-0 rounded">
                {{ form.media(id='upload', onchange='readURL(this);', class='form-control border-0') }}
                {{ form.media.label(id='upload-label', for='upload', class='font-weight-light text-muted') }}
                <div class="input-group-append">
                    <label for="upload" class="btn btn-light m-0 px-4"> 
                        <i class="fa fa-cloud-upload mr-2 text-muted"></i>
                        <small class="text-uppercase font-weight-bold text-muted">Choose file</small></label>
                </div>
            </div>
        </div>
        {% if form.media.errors %}
            <div class="card-footer">
            {% for error in form.media.errors %}
                    <span class="text-danger">{{ error }}</span>
                {% endfor %}
            </div>
        {% endif %}
    </div>
    <div class="modal fade" id="exampleModalCenter" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h6 class="modal-title" id="exampleModalLongTitle">New post</h6>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body bg-light">
                <div class="image-area"><img id="imageResult" src="#" alt="" class="img-fluid shadow-sm mx-auto d-block rounded-0"></div>
    
            </div>
            <div class="modal-footer post-caption-box">
                <ul class="list-group list-group-flush" style="width: 85%;">
                    {{ form.content(class="text-muted caption-box", id="caption", placeholder="Add a caption..") }}
                    {% if form.content.errors %}
                            {% for error in form.content.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                    {% endif %}
                </ul>
                {{ form.submit(class="btn post-btn") }}
            </div>
          </div>
        </div>
    </div>
</form>

<script type="text/javascript">
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#imageResult')
                    .attr('src', e.target.result);
            };
            reader.readAsDataURL(input.files[0]);
            
            $('#exampleModalCenter').modal('show');
        }
    }

    $(function () {
        $('#upload').on('change', function () {
            readURL(input);
        });
    });

    var input = document.getElementById( 'upload' );
    var infoArea = document.getElementById( 'upload-label' );

    input.addEventListener('change', showFileName);
    function showFileName( event ) {
        var input = event.srcElement;
        var fileName = input.files[0].name;
        infoArea.textContent = 'File name: ' + fileName;
    }

</script>
{% endblock %}

application/RFGram/application/templates/post.html
{% extends "layout.html" %}
{% block content %}
    <div class="card article">
        <div class="card-header">
            <img  class="account-img rounded-circle" src="../../{{ get_file_url('profile_pics/' + post.author.image_file) }}">
            <a class="text-dark user-link" href="{{ url_for('views.get_user', username=post.author.username) }}">{{ post.author.username }}</a>
        </div>

        {% if post.media %}
            <div class="main-img-wrapper bg-light">
                <img src="../../{{ get_file_url('media/' + post.media) }}" class="card-img-top post-media rounded-0" alt="">
            </div>
        {% endif %}
        <div class="card-body pb-2">
            <div class="card-text post-meta-data">
                {% if post.user_liked(current_user) %}
                        <span id="l-{{ post.pid }}" class="up-info like liked"><i class='fas fa-heart'></i></span>
                {% else %}
                    <span id="l-{{ post.pid }}" class="up-info like"><i class='far fa-heart'></i></span>
                {% endif %}

                <span class="up-info"><i class="far fa-comment"></i></span>
                <span id="sh-{{ post.pid }}" class="up-info share"><i class="fa fa-share"></i></span>
                
                {% if post.author == current_user %}
                    <small class="float-right"><a class="text-danger" href="{{ url_for('views.delete_post', post_id=post.pid) }}">delete post</a></small>
                {% endif %}
                <div class="like-counter">
                    <span id="like-{{ post.pid }}" class="like-count">{{ post.get_likes_count() }}</span>
                    likes
                </div>
            </div>
            <span class="card-text"> 
                <a class="text-dark user-link " href="{{ url_for('views.get_user', username=post.author.username) }}">{{ post.author.username }}</a>
                {{ post.content }}
            </span>
            <div class="comments" id="comments-on-{{ post.pid }}">
                {% if post.comments %}
                    {% for comment in post.comments %}
                        <span class="comment" id="c{{ comment.cid }}">
                            <a class="text-dark user-link" href="{{ url_for('views.get_user', username=comment.author.username) }}">{{ comment.author.username }}</a>
                                {{ comment.content }}
                                {% if comment.author == current_user %}
                                    <small class="float-right delete-comment" id="comment-{{ comment.cid }}">
                                        <a class="text-danger" href="#">delete</a>
                                    </small>
                                {% endif %}
                        </span>
                    {% endfor %}
                {% endif %}
            </div>
            <small class="text-muted text-uppercase">{{ post.get_timeago() }}</small>
        </div>
        <ul class="list-group list-group-flush">
            {% if current_user.is_authenticated %}
            <textarea class="text-muted comment-box make-comment border-bottom pl-2 pr-2" id="comment-on-{{ post.pid }}" placeholder="Add a comment.."></textarea>
            <button class="btn post-comment" id="c-{{ post.pid }}">Post</button>
            {% else %}
                <div class="p-2">
                    <a href="{{ url_for('views.login') }}" class="text-muted">Login to comment</a>
                </div>
            {% endif %}
        </ul>
    </div>
{% endblock content %}